---
title: "Module 2 - Data Vizualization and Basic Transformations"
editor: source
---

<!-- 
See issue with underscores in MathJax equations here: https://gohugo.io/content-management/formats/#issues-with-markdown
The solution, put backticks (`) around the LaTeX equation
-->

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']],
    displayMath: [['$$','$$'], ['\[','\]']],
    processEscapes: true,
    processEnvironments: true,
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
    TeX: { equationNumbers: { autoNumber: "AMS" },
         extensions: ["AMSmath.js", "AMSsymbols.js"] }
  }
});
</script>

<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>


### Learning Objectives

* Data Visualization for Numerical and Categorical Variables
* Grammar of Graphics
* tidyverse code conventions 
* Basic Data Transofrmations


### Readings

* __RDS__ (R for Data Science): [Chapters 1-4](https://r4ds.hadley.nz/whole-game)

### Additional Resources:

* [_Fundamentals of Data Visualization_](https://clauswilke.com/dataviz/). Claus O. Wilkey. (2019). O'Reilly. 

This is my favorite modern book on data visualization, and it also uses ggplot2 as the primary tool. If you are uncertain about what visualizations might be appropriate for a given
problem, this is a good place to check for inspiration. The intended audience is scientists but it is equally relevant for people working in other industries. Chapters 1-5 and Chapter 29
would be good additional readings if you wanted to go a little more in depth. 

*[_A Layered Grammar of Graphics_](https://vita.had.co.nz/papers/layered-grammar.pdf). Hadley Wickham. _Journal of computational and graphical statistics_ 19.1 (2010): 3-28.

This paper explains the concepts and thinking behind ggplot2.

*[ggplot2 website](https://ggplot2.tidyverse.org/). This is another excellent source of resources and information on ggplot2




### Videos



