-
-
title: "Syllabus"
---

**Instructor:** George Hagstrom, Ph.D.
**Class Meetup:** TBD
**Office Hours:** By appointment abd TBD
**Email:** <a href="mailto:george.hagstrom@cuny.edu">george.hagstrom@cuny.edu</a>


### Course Description

In this course students will learn about core concepts of contemporary data collection and its management.
Topics will include an introduction to programming and collaboration in statistical software packages, data visualization techniques,
data wrangling and transformation, exploratory data analysis and data quality checks, data acquisition from a variety of
sources including databases and the web, tools for working with textual and graph data, feature engineering, and working with
large datasets in a cloud computing environment.

Students will complete a project to create a working system for a large volume of data using publicly available data sets.

### Course Learning Outcomes:

By then end of the course, students should be able to:

*Load data into R from various data sources, including CSV files, Excel spreadsheets, relational databases,
APIs, and web pages.
* Perform various data cleansing and transformation work, including splitting, combining; resampling;
variable creation; data aggregation; sorting and filtering data; strategies for working with outliers and
missing data; data visualization and analysis in support of data cleansing activities.
* Understand different information architectures, data types, and data structures.
* Understand relational and non-relational database design and querying.
* Cover relevant ethical issues including data privacy and misinformation.



### Program Learning Outcomes addressed by the course:

* Business Understanding. Apply frameworks and processes to build out data analytics solutions from
understanding of business goals.
* Data Culture. Embody and champion the highest standards for the ethical and moral use of data;
understand issues related to data privacy and data security.
* Solid foundational data programming skills, using industry standard tools, essential algorithms, and design
patterns for working with structured data, unstructured data and big data.
* Data understanding. Collect, describe, model, explore and verify data.
* Data preparation. Selecting, cleaning, constructing, integrating, and formatting data.


### How is this course relevant for data analytics professionals?

Most data analytics professionals spend most of their time getting data and preparing it for analysis. This is the
course that teaches these key skills, as we work with both structured and unstructured data.

### Grading


* [Meetup Reflections](/assignments/participation) (10%)
* [Labs](/assignments/labs) (50%)
* [TidyVerse Recipes](10%)
* [Project](/assignments/project) (30%)



#### Grade Distribution

Quality of Performance                     | Letter Grade | Range %   | GPA  |
-------------------------------------------|:------------:|:---------:|:----:|
Excellent - work is of exceptional quality |      A       | 93 - 100  |  4   |
Excellent                                  |      A-      | 90 - 92.9 | 3.7  |
Good - work is above average               |      B+      | 87 - 89.9 | 3.3  |
Satisfactory                               |      B       | 83 - 86.9 |  3   |
Below Average                              |      B-      | 80 - 82.9 | 2.7  |
Poor                                       |      C+      | 77 - 79.9 | 2.3  |
Poor                                       |      C       | 70 - 76.9 |  2   |
Failure                                    |      F       |   < 70    |  0   |

### How This Course Works

This course is conducted entirely online. Each week, you will have various resources made available, including weekly readings from the textbooks and occasionally additional readings provided by the instructor. Most weeks will have homework assignments and labs to be submitted (although some chapters will take more than one week, see the [schedule](/course-overview/schedule/) for details). There will also be a presentation required and a forum post introduction required. You are expected to complete all assignments by their due dates.

**You are expected to attend or watch every Meetup.** I highly recommend attending the Meetups live if possible but understand that may not be possible for everyone. Recordings will be made available by the next morning on the [Meetups page](/course-overview/meetups/). In addition to highlighting key concepts from each learning module, some topics will be discussed that are not in the textbook. Moreover, we regularly make announcements in the Meetups that will be important to being successful in this course. At the end of each Meetup there will be a short reflective exercise. These will contribute to your participation grade.

The culmination of the course will be the presentation of the analysis of a dataset of your choosing. See the [project](/assignments/project/) for more information.

### Textbooks and Course Materials

* _R for Data Science (2e)_ by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund. This is the primary text for the
course. Available online for free at: [https://r4ds.hadley.nz/](https://r4ds.hadley.nz/)

*_Happy Git and GitHub for the userR_, Jennifer Bryan. Available online for free at [happygitwithr.com/](https://happygitwithr.com/). This is a short book introducing git and github 
from the perspective of the statistical computing and data science use cases, and showing how it can be integrated with R and RStudio.


* _Text Mining with R: A Tidy Approach_, Julia Silge and David Robinson. O’Reilly, 2017. Available
online for free at [https://www.tidytextmining.com/](https://www.tidytextmining.com/)



### Accessibility and Accommodations

The CUNY School of Professional Studies is firmly committed to making higher education accessible to students with disabilities by removing architectural barriers and providing programs and support services necessary for them to benefit from the instruction and resources of the University. Early planning is essential for many of the resources and accommodations provided. Please see: [http://sps.cuny.edu/student_services/disabilityservices.html](http://sps.cuny.edu/student_services/disabilityservices.html)

### Online Etiquette and Anti-Harassment Policy

The University strictly prohibits the use of University online resources or facilities, including Blackboard, for the purpose of harassment of any individual or for the posting of any material that is scandalous, libelous, offensive or otherwise against the University’s policies.  Please see: [http://media.sps.cuny.edu/filestore/8/4/9_d018dae29d76f89/849_3c7d075b32c268e.pdf](http://media.sps.cuny.edu/filestore/8/4/9_d018dae29d76f89/849_3c7d075b32c268e.pdf)

### Academic Integrity

Academic dishonesty is unacceptable and will not be tolerated. Cheating, forgery, plagiarism and collusion in dishonest acts undermine the educational mission of the City University of New York and the students' personal and intellectual growth. Please see: [http://media.sps.cuny.edu/filestore/8/3/9_dea303d5822ab91/839_1753cee9c9d90e9.pdf](http://media.sps.cuny.edu/filestore/8/3/9_dea303d5822ab91/839_1753cee9c9d90e9.pdf)

### Student Support Services

If you need any additional help, please visit Student Support Services: 
[http://sps.cuny.edu/student_resources/](http://sps.cuny.edu/student_resources/)
