---
title: "Lab 5: Working with Text and Strings "
format: html
editor: source
---

# Overview

In this lab you will practice perform a series of exercises that use text and string manipulation to either analyze data with text, manipulate data containing strings, apply
regular expressions, or handle data files with unusual formats or text strings.

## Problems

**Problem 1.** Using the 173 majors listed in fivethirtyeight.com’s 
[College Majors dataset](https://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/), provide code that identifies the majors that contain either "DATA" or "STATISTICS"

**Problem 2** Write code that transforms the data below:

` [1] "bell pepper" "bilberry" "blackberry" "blood orange" `\
` [5] "blueberry" "cantaloupe" "chili pepper" "cloudberry" `\
` [9] "elderberry" "lime" "lychee" "mulberry" `\
` [13] "olive"  "salal berry" `\

Into a format like this:

` c("bell pepper", "bilberry", "blackberry", "blood orange", "blueberry", "cantaloupe", "chili pepper", "cloudberry", "elderberry", "lime", "lychee", "mulberry", "olive", "salal berry") `



**Problem 3** Describe, in words, what these regular expressions will match:

- ` (.)\1\1 `
- ` "(.)(.)\\2\\1" `
- ` (..)\1 `
- ` "(.).\\1.\\1" `
- ` "(.)(.)(.).*\\3\\2\\1" `

**Problem 4.** Construct regular expressions to match words that:

- Start and end with the same character.
- Contain a repeated pair of letters (e.g. "church" contains "ch" repeated twice.)
- Contain one letter repeated in at least three places (e.g. "eleven" contains three "e"s.)
